### ISSUE TITLE
Conditions signaled from promises are invisible to the invoking environment

### ISSUE THREAD

**Issue by tzakharko** [rstudio/promises#70]
It seems that any signaled condition inside a promise is gobbled up by some hidden mechanism and will not be visible to the external handlers. The attached code illustrates this with messages (because they have a clear side effect), but I also tried it with other signals with the same effect. 

Is there any obvious way to access signaled conditions  outside of using external mechanisms (e.g. a  callback).

``` r
library(promises)

withCallingHandlers({
    promise(~ {
     later::later(~ {
        message("this is a message")
        resolve(TRUE)
     })
    }) %>% finally(~ {
      message("we are done")
      cat("Promise is resovled\n")
    })
  
  
    while(!later::loop_empty()) {
      later::run_now()
      Sys.sleep(0.1)
      message("from the main loop")
    }
  },
  message = function(cnd) {
    cat("Got message:", cnd$message)
  }
)
#> Got message: from the main loop
#> from the main loop
#> Promise is resovled
#> Got message: from the main loop
#> from the main loop
#> Got message: from the main loop
#> from the main loop
```

**Comment by tzakharko** [comment]
After digging a bit into this I realized that this is a limitation of `later`, so I will ask this question there.

**Comment by bartekch** [comment]
@tzakharko  what issue in `later` is this? Is it solved maybe?

**Comment by gadenbuie** [comment]
@tzakharko Thanks for checking back in! In terms of the snippet in this issue; it's definitely not expected to work.  The conditions aren't signaled in a place visible to `withCallingHandlers()` in the parent process. To handle errors, you need to use `catch()` or the `onRejected` argument of `then()`. You might be able to catch other conditions in this way, too, or you might need to bring the condition handler into the block being evaluated in a promise.

**Comment by bartekch** [comment]
@gadenbuie my case is almost exactly the same as OP - I want to intercept messages signaled in `onFulfilled` (or `onRejected`, same story). Simplest example.
```r
withCallingHandlers(
  {
    message("This message will be caught")
    promises::future_promise(Sys.sleep(1)) |>
      promises::then(function() message("I want this meesage to be caught as well"))
  },
  message = function(cnd) {
    message("Got message: ", cnd$message)
  }
)
```

I thought that it would work, since callback is run in the original process. I also got confused by the sentence `However, it’s perfectly fine to read reactive values/expressions from inside a promise handler. Handlers run in the original process, not a child process, so reactive operations are allowed.` in [vignette about promises in Shiny](https://rstudio.github.io/promises/articles/shiny.html#shiny-specific-caveats-and-limitations) (my actual case is Shiny app, but it doesn't really matter).

From your comments I infer that it does NOT work like that. And, after some consideration, it actually makes some sense, because whole call to `withCallingHandlers` is completed before promise is resolved. It's just a little less obvious when running sequentially (or inside Shiny, as I did). Hence I won't open another issue for this.

@jcheng5 I'm not exactly sure how should I use domains to address my issue, but anyway it seems like way too complicated for what I need, thanks for suggestion though!

In the meantime I believe I found [the forementioned issue in `later`](https://github.com/r-lib/later/issues/108) - still open though.
